### ISSUE TITLE
fr: Add "automatic upload" as a optional checkbox

### ISSUE THREAD

**Issue by sebastianowy** [marzetz/JiraTracker#1]
# Feature description

Currently time is logged automatically on the "stop" button click event. There is no way to decide if user wants to correct or reject the time record.
I suggest adding a checkbox "automatic upload" with `true` as default value to let the extension work as it currently is. If the checkbox is unchecked, users need to confirm, that they want to add the record to a worklog.

# Use Case

This would prevent adding a record to worklog that needs to be rejected due to various business/human reasons.

**Comment by marzetz** [comment]
Feature introduced in the newest version
